# Generated by Django 5.2.5 on 2025-09-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
